# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'b8f4f598-9390-48f0-852b-b0fef62b9f27'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'NewGroup'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ValeriiaHlotka/Encyclopsedia/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName Encyclopsedia'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
